select a.CAR_ID, a.CAR_TYPE, CAST(a.DAILY_FEE * 30*(1-b.DISCOUNT_RATE *0.01)AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a join CAR_RENTAL_COMPANY_DISCOUNT_PLAN b
on a.CAR_TYPE = b.CAR_TYPE
where a.CAR_ID not in(
select distinct c.CAR_ID
from CAR_RENTAL_COMPANY_RENTAL_HISTORY c
where c.START_DATE <= '2022-11-30' and c.END_DATE >= '2022-11-01')
and a.CAR_TYPE in('SUV','세단')
and b.DURATION_TYPE = '30일 이상'
and a.DAILY_FEE * 30 *(1-b.DISCOUNT_RATE *0.01) >= 500000
and a.DAILY_FEE * 30 * (1-b.DISCOUNT_RATE * 0.01) < 2000000
order by FEE DESC, CAR_TYPE ASC, CAR_ID DESC