select ID,
case
    when SIZE_OF_COLONY <= 100 THEN 'LOW'
    when SIZE_OF_COLONY > 100 && SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
    when SIZE_OF_COLONY > 1000 THEN 'HIGH'
end SIZE
from ECOLI_DATA
order by ID