select p.PRODUCT_ID, PRODUCT_NAME, SUM(o.AMOUNT * p.PRICE) AS TOTAL_SALES
from FOOD_PRODUCT p
join FOOD_ORDER o
on p.PRODUCT_ID = o.PRODUCT_ID
where o.PRODUCE_DATE like "2022-05%"
group by p.PRODUCT_ID
order by TOTAL_SALES DESC, p.PRODUCT_ID 